name: Update Indexes
on:
  schedule:
    - cron: "33 0 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: http-cache-${{ github.run_id }}-${{ github.run_number }}
          restore-keys: |
            http-cache-
          path: /tmp/http_cache.sqlite
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - run: pip install -r codex/requirements.txt

      - name: Update Indexes Data
        run: python3 codex/main.py --index

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: bot/update-indexes
          delete-branch: true
          commit-message: "chore: update indexes [bot]"
          title: "[bot] Update Indexes"
          body: "See files changed"
